import argparse
import os
import sys
from pathlib import Path
import subprocess
import shutil
import numpy as np
# torch, cv2, tqdm are imported lazily inside CUT3R functions (not needed for COLMAP mode)


# LLFF path for COLMAP-based pose generation
LLFF_PATH = Path("/workspace/sim-animate-environment/infinite-simul-realtime-4d-gaussian-vgg/third_party/infinite_simul_spacetime_gaussian/thirdparty/LLFF")

# CUT3R paths
CUT3R_ROOT = Path("/mnt/c/Users/kodeb/OneDrive/Desktop/vicks/Infinite-Simul/sim-animate-environment/CUT3R")
CUT3R_DEFAULT_CKPT = Path("/mnt/c/Users/kodeb/OneDrive/Desktop/vicks/Infinite-Simul/sim-animate-environment/checkpoints/cut3r/cut3r_512_dpt_4_64.pth")


def rotmat2qvec(R):
    Rxx, Ryx, Rzx, Rxy, Ryy, Rzy, Rxz, Ryz, Rzz = R.flat
    K = np.array([
        [Rxx - Ryy - Rzz, 0, 0, 0],
        [Ryx + Rxy, Ryy - Rxx - Rzz, 0, 0],
        [Rzx + Rxz, Rzy + Ryz, Rzz - Rxx - Ryy, 0],
        [Ryz - Rzy, Rzx - Rxz, Rxy - Ryx, Rxx + Ryy + Rzz]]) / 3.0
    eigvals, eigvecs = np.linalg.eigh(K)
    qvec = eigvecs[[3, 0, 1, 2], np.argmax(eigvals)]
    if qvec[0] < 0:
        qvec *= -1
    return qvec

def qvec2rotmat(qvec):
    return np.array([
        [1 - 2 * qvec[2]**2 - 2 * qvec[3]**2,
         2 * qvec[1] * qvec[2] - 2 * qvec[0] * qvec[3],
         2 * qvec[3] * qvec[1] + 2 * qvec[0] * qvec[2]],
        [2 * qvec[1] * qvec[2] + 2 * qvec[0] * qvec[3],
         1 - 2 * qvec[1]**2 - 2 * qvec[3]**2,
         2 * qvec[2] * qvec[3] - 2 * qvec[0] * qvec[1]],
        [2 * qvec[3] * qvec[1] - 2 * qvec[0] * qvec[2],
         2 * qvec[2] * qvec[3] + 2 * qvec[0] * qvec[1],
         1 - 2 * qvec[1]**2 - 2 * qvec[2]**2]])

def average_quaternions(quats):
    avg_quat = np.mean(quats, axis=0)
    avg_quat /= np.linalg.norm(avg_quat)
    return avg_quat

def get_video_dims(video_path):
    cmd = [
        "ffprobe", "-v", "error", "-select_streams", "v:0",
        "-show_entries", "stream=width,height", "-of", "csv=p=0",
        str(video_path)
    ]
    res = subprocess.check_output(cmd).decode("utf-8").strip()
    w, h = map(int, res.split(","))
    return w, h

def orthogonalize(R):
    U, S, Vt = np.linalg.svd(R)
    R_ortho = U @ Vt
    if np.linalg.det(R_ortho) < 0:
        Vt[-1] *= -1
        R_ortho = U @ Vt
    return R_ortho

# LLFF convention matrix: converts OpenCV c2w to LLFF format.
M_LLFF = np.array([[0, 1, 0],
                   [1, 0, 0],
                   [0, 0, -1]], dtype=np.float64)


# =============================================================================
# COLMAP-based pose generation (existing, unchanged)
# =============================================================================
def generate_poses_colmap(video_folder, output_name="poses_bounds.npy"):
    """Generate poses_bounds.npy using COLMAP + LLFF (multi-view SfM).
    
    Extracts one frame per video, runs COLMAP feature extraction/matching/mapping,
    then uses LLFF's pose utilities to produce the standard poses_bounds.npy.
    """
    video_folder = Path(video_folder)
    video_files = sorted(video_folder.glob("cam*.mp4"))
    if not video_files:
        print(f"No video files found in {video_folder}")
        return
    
    print(f"Found {len(video_files)} videos in {video_folder}")
    
    target_w, target_h = get_video_dims(video_files[0])
    print(f"Targeting resolution: {target_w}x{target_h} (from {video_files[0].name})")
    
    images_dir = video_folder / "images"
    images_dir.mkdir(exist_ok=True)
    
    print("Extracting frames for COLMAP...")
    for video in video_files:
        output_pattern = images_dir / f"{video.stem}_0001.jpg"
        if not output_pattern.exists():
            subprocess.run([
                "ffmpeg", "-i", str(video),
                "-vf", f"scale={target_w}:{target_h}",
                "-frames:v", "1",
                "-q:v", "2",
                "-loglevel", "error",
                str(images_dir / f"{video.stem}_%04d.jpg")
            ], check=True)
    
    print("Running COLMAP via LLFF...")
    llff_dir = str(LLFF_PATH)
    sys.path.insert(0, llff_dir)
    
    try:
        from llff.poses.pose_utils import gen_poses
        success = gen_poses(str(video_folder), 'exhaustive_matcher')
        if not success:
            raise RuntimeError("gen_poses returned failure")
    except Exception as e:
        print(f"COLMAP/LLFF failed: {e}")
        print("Falling back to running imgs2poses.py as subprocess...")
        subprocess.run([
            "python3", str(LLFF_PATH / "imgs2poses.py"), str(video_folder)
        ], check=True)
    
    pb_file = video_folder / "poses_bounds.npy"
    if not pb_file.exists():
        raise RuntimeError("poses_bounds.npy was not generated by COLMAP/LLFF")
    
    poses_bounds = np.load(pb_file)
    print(f"✅ COLMAP generated poses_bounds.npy: shape={poses_bounds.shape}")
    
    if output_name != "poses_bounds.npy":
        output_path = video_folder / output_name
        shutil.copy2(pb_file, output_path)
        print(f"✅ Copied to {output_path}")
    
    colmap_0 = video_folder / "colmap_0"
    sparse_src = video_folder / "sparse" / "0"
    sparse_dst = colmap_0 / "sparse" / "0"
    if sparse_src.exists() and not sparse_dst.exists():
        sparse_dst.mkdir(parents=True, exist_ok=True)
        for f in sparse_src.iterdir():
            shutil.copy2(f, sparse_dst / f.name)
        print(f"✅ Copied sparse model to {sparse_dst}")
    
    if images_dir.exists():
        shutil.rmtree(images_dir)
    sparse_root = video_folder / "sparse"
    if sparse_root.exists():
        shutil.rmtree(sparse_root)
    db_file = video_folder / "database.db"
    if db_file.exists():
        db_file.unlink()
    
    print(f"✅ COLMAP pose generation complete for {video_folder}")


# =============================================================================
# COLMAP binary writers (for CUT3R output compatibility)
# =============================================================================
import struct
import collections

CameraModel = collections.namedtuple("CameraModel", ["model_id", "model_name", "num_params"])
CAMERA_MODEL_PINHOLE = CameraModel(model_id=1, model_name="PINHOLE", num_params=4)


def write_cameras_binary(cameras, path):
    """Write COLMAP cameras.bin file.
    
    cameras: list of dicts with keys: id, width, height, fx, fy, cx, cy
    """
    with open(path, "wb") as f:
        f.write(struct.pack("<Q", len(cameras)))
        for cam in cameras:
            camera_id = cam["id"]
            model_id = CAMERA_MODEL_PINHOLE.model_id
            width = int(cam["width"])
            height = int(cam["height"])
            params = [cam["fx"], cam["fy"], cam["cx"], cam["cy"]]
            f.write(struct.pack("<I", camera_id))
            f.write(struct.pack("<i", model_id))
            f.write(struct.pack("<Q", width))
            f.write(struct.pack("<Q", height))
            for p in params:
                f.write(struct.pack("<d", p))


def write_images_binary(images, path):
    """Write COLMAP images.bin file.
    
    images: list of dicts with keys: id, qvec(4), tvec(3), camera_id, name
    """
    with open(path, "wb") as f:
        f.write(struct.pack("<Q", len(images)))
        for img in images:
            image_id = img["id"]
            qvec = img["qvec"]
            tvec = img["tvec"]
            camera_id = img["camera_id"]
            name = img["name"]
            
            f.write(struct.pack("<I", image_id))
            for q in qvec:
                f.write(struct.pack("<d", q))
            for t in tvec:
                f.write(struct.pack("<d", t))
            f.write(struct.pack("<I", camera_id))
            # Write image name as null-terminated string
            for ch in name:
                f.write(struct.pack("<c", ch.encode("utf-8")))
            f.write(struct.pack("<c", b"\x00"))
            # Number of 2D points (we write 0 — no 2D-3D correspondences needed)
            f.write(struct.pack("<Q", 0))


def write_points3D_binary(points3D, path):
    """Write COLMAP points3D.bin file.
    
    points3D: dict of {point_id: {"xyz": (3,), "rgb": (3,), "error": float}}
    """
    import numpy as np
    num_points = len(points3D)
    with open(path, "wb") as f:
        f.write(struct.pack("<Q", num_points))
        
        # Prepare structured array for fast writing
        # POINT3D_ID (Q:8) | X, Y, Z (ddd:24) | R, G, B (BBB:3) | ERROR (d:8) | TRACK_LENGTH (Q:8)
        data = np.zeros(num_points, dtype=[
            ('id', '<Q'),
            ('xyz', '<d', 3),
            ('rgb', '<B', 3),
            ('error', '<d'),
            ('track_len', '<Q')
        ])
        
        # This is still a loop but it only happens once during pose generation
        # and dictionaries are inherently slow to iterate.
        # We can optimize if points3D was already a numpy array, but for now
        # let's just make the writing part fast.
        for i, (point_id, pt) in enumerate(points3D.items()):
            data[i]['id'] = point_id
            data[i]['xyz'] = pt["xyz"]
            data[i]['rgb'] = pt["rgb"]
            data[i]['error'] = pt.get("error", 0.0)
            data[i]['track_len'] = 0
            
        data.tofile(f)



# =============================================================================
# CUT3R-based pose generation
# =============================================================================
def _load_cut3r_model(model_path, device="cuda"):
    """Load CUT3R model with proper path setup."""
    import torch
    cut3r_root = str(CUT3R_ROOT)
    if cut3r_root not in sys.path:
        sys.path.insert(0, cut3r_root)
    
    # add_ckpt_path sets up the sibling import path for dust3r
    from add_ckpt_path import add_path_to_dust3r
    add_path_to_dust3r(str(model_path))
    
    from src.dust3r.model import ARCroco3DStereo
    
    print(f"Loading CUT3R model from {model_path}...")
    model = ARCroco3DStereo.from_pretrained(str(model_path)).to(device)
    model.eval()
    print("✅ CUT3R model loaded")
    return model


def _run_cut3r_inference(model, img_paths, size=512, device="cuda"):
    """Run CUT3R inference on a list of image paths.
    
    Returns:
        pts3d_self: (B, H, W, 3) per-view 3D points in self-view coords
        pts3d_world: (B, H, W, 3) per-view 3D points in world coords  
        c2w_poses: (B, 4, 4) camera-to-world poses
        focals: (B,) estimated focal lengths
        pp: (B, 2) principal points
        conf_self: (B, H, W) confidence maps
        colors: (B, H, W, 3) image colors [0,1]
    """
    import torch
    from src.dust3r.utils.image import load_images_512
    from src.dust3r.inference import inference
    from src.dust3r.utils.camera import pose_encoding_to_camera
    from src.dust3r.post_process import estimate_focal_knowing_depth
    from src.dust3r.utils.geometry import geotrf
    
    # Prepare input views — use load_images_512 to force uniform size
    images = load_images_512(img_paths, size=size)
    views = []
    for i in range(len(images)):
        view = {
            "img": images[i]["img"],
            "ray_map": torch.full(
                (images[i]["img"].shape[0], 6,
                 images[i]["img"].shape[-2], images[i]["img"].shape[-1]),
                torch.nan,
            ),
            "true_shape": torch.from_numpy(images[i]["true_shape"]),
            "idx": i,
            "instance": str(i),
            "camera_pose": torch.from_numpy(np.eye(4, dtype=np.float32)).unsqueeze(0),
            "img_mask": torch.tensor(True).unsqueeze(0),
            "ray_mask": torch.tensor(False).unsqueeze(0),
            "update": torch.tensor(True).unsqueeze(0),
            "reset": torch.tensor(False).unsqueeze(0),
        }
        views.append(view)
    
    # Run inference
    print(f"Running CUT3R inference on {len(views)} views...")
    outputs, state_args = inference(views, model, device)
    
    # Extract results
    pts3d_self_ls = [output["pts3d_in_self_view"].cpu() for output in outputs["pred"]]
    conf_self_ls = [output["conf_self"].cpu() for output in outputs["pred"]]
    pts3d_self = torch.cat(pts3d_self_ls, 0)  # (B, H, W, 3)
    conf_self = torch.cat(conf_self_ls, 0)  # (B, H, W)
    
    # Recover camera poses (c2w in OpenCV convention)
    pr_poses = [
        pose_encoding_to_camera(pred["camera_pose"].clone()).cpu()
        for pred in outputs["pred"]
    ]
    c2w_poses = torch.cat(pr_poses, 0)  # (B, 4, 4)
    
    # Transform self-view points to world coords using c2w
    pts3d_world_ls = []
    for pose, pself in zip(pr_poses, pts3d_self_ls):
        pts3d_world_ls.append(geotrf(pose, pself.unsqueeze(0) if pself.dim() == 3 else pself))
    pts3d_world = torch.cat(pts3d_world_ls, 0)  # (B, H, W, 3)
    
    # Estimate focal length
    B, H, W, _ = pts3d_self.shape
    pp = torch.tensor([W // 2, H // 2], device=pts3d_self.device).float().repeat(B, 1)
    focals = estimate_focal_knowing_depth(pts3d_self, pp, focal_mode="weiszfeld")
    
    # Extract colors
    colors = torch.cat([
        0.5 * (output["img"].permute(0, 2, 3, 1).cpu() + 1.0)
        for output in outputs["views"]
    ], 0)  # (B, H, W, 3)
    
    return pts3d_self, pts3d_world, c2w_poses, focals, pp, conf_self, colors


def _subsample_points_by_confidence(pts3d, colors, conf, max_points=50000, conf_percentile=50):
    """Subsample dense point cloud by confidence, then random if still too many.
    
    Args:
        pts3d: (H, W, 3) or (N, 3) points
        colors: (H, W, 3) or (N, 3) RGB [0,1]
        conf: (H, W) or (N,) confidence
        max_points: maximum number of points to return
        conf_percentile: percentile threshold for confidence filtering
    
    Returns:
        xyz: (M, 3) subsampled points
        rgb: (M, 3) subsampled colors [0, 255]
    """
    import torch
    if pts3d.dim() == 3:
        pts3d = pts3d.reshape(-1, 3)
        colors = colors.reshape(-1, 3)
        conf = conf.reshape(-1)
    
    # Remove NaN/inf points
    valid = torch.isfinite(pts3d).all(dim=-1) & torch.isfinite(conf) & (conf > 0)
    pts3d = pts3d[valid]
    colors = colors[valid]
    conf = conf[valid]
    
    if len(pts3d) == 0:
        return np.zeros((0, 3)), np.zeros((0, 3), dtype=np.uint8)
    
    # Confidence filter: keep points above percentile threshold
    conf_threshold = torch.quantile(conf, conf_percentile / 100.0)
    mask = conf >= conf_threshold
    pts3d = pts3d[mask]
    colors = colors[mask]
    conf = conf[mask]
    
    # Random subsample if still too many
    if len(pts3d) > max_points:
        # Weight by confidence for importance sampling
        weights = conf / conf.sum()
        indices = torch.multinomial(weights, max_points, replacement=False)
        pts3d = pts3d[indices]
        colors = colors[indices]
    
    xyz = pts3d.numpy()
    rgb = (colors.numpy() * 255).clip(0, 255).astype(np.uint8)
    return xyz, rgb


def generate_poses_cut3r(video_folder, output_name="poses_bounds.npy",
                         model_path=None, device="cuda", size=512,
                         max_points_per_view=4000):

    """Generate poses_bounds.npy using CUT3R (dense regression-based 3D reconstruction).
    
    Extracts one frame per video, runs CUT3R to get camera poses plus dense 3D points,
    then produces poses_bounds.npy in LLFF format and writes COLMAP-compatible sparse model.
    
    Args:
        video_folder: Path to folder containing cam*.mp4 files
        output_name: Output filename for poses_bounds
        model_path: Path to CUT3R checkpoint (.pth)
        device: torch device
        size: CUT3R input size (512 for the DPT model)
        max_points_per_view: Maximum points per view for initialization
    """
    import torch
    video_folder = Path(video_folder)
    video_files = sorted(video_folder.glob("cam*.mp4"))
    if not video_files:
        print(f"No video files found in {video_folder}")
        return
    
    n_cams = len(video_files)
    print(f"Found {n_cams} videos in {video_folder}")
    
    if model_path is None:
        model_path = CUT3R_DEFAULT_CKPT
    model_path = Path(model_path)
    
    # Step 1: Extract 1 frame per video
    target_w, target_h = get_video_dims(video_files[0])
    print(f"Video resolution: {target_w}x{target_h}")
    
    images_dir = video_folder / "images_cut3r_tmp"
    images_dir.mkdir(exist_ok=True)
    
    img_paths = []
    print("Extracting frames for CUT3R...")
    for video in video_files:
        output_path = images_dir / f"{video.stem}.jpg"
        if not output_path.exists():
            subprocess.run([
                "ffmpeg", "-i", str(video),
                "-frames:v", "1",
                "-q:v", "2",
                "-loglevel", "error",
                str(output_path)
            ], check=True)
        img_paths.append(str(output_path))
    
    # Step 1b: Resize all frames to the same resolution (CUT3R requires uniform sizes for batching)
    # Use 1920x1080 (standard 16:9) which gives 512x288 = 32x18 patches after CUT3R rescaling
    # Avoids odd patch counts that cause CUDA indexing errors in RoPE
    import cv2
    target_res = (1920, 1080)  # w, h
    print(f"Normalizing all frames to {target_res[0]}x{target_res[1]} for CUT3R compatibility")
    for p in img_paths:
        img = cv2.imread(p)
        if img.shape[:2] != (target_res[1], target_res[0]):
            img_resized = cv2.resize(img, target_res, interpolation=cv2.INTER_LANCZOS4)
            cv2.imwrite(p, img_resized)
            print(f"  Resized {Path(p).name}: {img.shape[1]}x{img.shape[0]} -> {target_res[0]}x{target_res[1]}")
    
    # Step 2: Load CUT3R model and run inference
    model = _load_cut3r_model(model_path, device)
    pts3d_self, pts3d_world, c2w_poses, focals, pp, conf_self, colors = \
        _run_cut3r_inference(model, img_paths, size=size, device=device)
    
    B, H, W, _ = pts3d_self.shape
    print(f"CUT3R output: {B} views, {H}x{W} resolution")
    
    # Step 3: Build poses_bounds.npy in LLFF format
    # LLFF format: each row = [R(3x3) flattened | t(3) | hwf(3) | near | far] = 17 values
    # The R,t are in LLFF convention (DRB): rows = [-up, right, -forward]
    poses_bounds_rows = []
    
    for i in range(B):
        c2w = c2w_poses[i].numpy()  # 4x4, OpenCV convention
        R_cv = c2w[:3, :3]  # OpenCV rotation
        t_cv = c2w[:3, 3]   # OpenCV translation
        
        # Convert OpenCV c2w rotation to LLFF convention
        # LLFF convention: row0 = -up (OpenCV row1), row1 = right (OpenCV row0), row2 = -forward (-OpenCV row2)
        R_llff = M_LLFF @ R_cv
        t_llff = M_LLFF @ t_cv
        
        # Orthogonalize to ensure proper rotation matrix
        R_llff = orthogonalize(R_llff)
        
        # Focal length: CUT3R estimates focal for the resized image (HxW)
        # Scale to original image dimensions
        focal_cut3r = focals[i].item()
        scale_w = target_w / W
        scale_h = target_h / H
        focal_orig = focal_cut3r * max(scale_w, scale_h)
        
        # Compute near/far from depth (z-values in self-view)
        depths = pts3d_self[i, :, :, 2]  # (H, W)
        valid_depths = depths[torch.isfinite(depths) & (depths > 0)]
        if len(valid_depths) > 0:
            near = torch.quantile(valid_depths, 0.02).item()
            far = torch.quantile(valid_depths, 0.98).item()
        else:
            near = 0.1
            far = 100.0
        # Safety margins
        near = max(near * 0.8, 0.01)
        far = far * 1.2
        
        # Pack as LLFF: [3x5 matrix flattened to 15] ++ [near, far]
        # 3x5 matrix = [R(3x3) | t(3x1) | hwf(3x1)]
        hwf = np.array([target_h, target_w, focal_orig])
        pose_3x5 = np.concatenate([R_llff, t_llff.reshape(3, 1), hwf.reshape(3, 1)], axis=1)
        row = np.concatenate([pose_3x5.flatten(), np.array([near, far])])
        poses_bounds_rows.append(row)
    
    poses_bounds = np.array(poses_bounds_rows, dtype=np.float64)
    
    # Save poses_bounds.npy
    pb_path = video_folder / output_name
    np.save(pb_path, poses_bounds)
    print(f"✅ CUT3R generated {output_name}: shape={poses_bounds.shape}")
    
    # Create COLMAP sparse structure
    colmap_dir = video_folder / "colmap_0"
    sparse_dir = colmap_dir / "sparse" / "0"
    manual_dir = colmap_dir / "manual"
    
    sparse_dir.mkdir(parents=True, exist_ok=True)
    manual_dir.mkdir(parents=True, exist_ok=True)


    
    # Build camera and image lists for COLMAP format
    colmap_cameras = []
    colmap_images = []
    all_points = {}
    point_id_counter = 1
    
    for i in range(B):
        cam_name = video_files[i].stem  # e.g., "cam00"
        c2w = c2w_poses[i].numpy()
        
        # Focal scaled to original resolution
        focal_cut3r = focals[i].item()
        scale_w = target_w / W
        scale_h = target_h / H
        fx = focal_cut3r * scale_w
        fy = focal_cut3r * scale_h
        cx = target_w / 2.0
        cy = target_h / 2.0
        
        colmap_cameras.append({
            "id": i + 1,
            "width": target_w,
            "height": target_h,
            "fx": fx,
            "fy": fy,
            "cx": cx,
            "cy": cy,
        })
        
        # Convert c2w to w2c for COLMAP
        w2c = np.linalg.inv(c2w)
        R_w2c = w2c[:3, :3]
        t_w2c = w2c[:3, 3]
        qvec = rotmat2qvec(R_w2c)
        
        colmap_images.append({
            "id": i + 1,
            "qvec": qvec,
            "tvec": t_w2c,
            "camera_id": i + 1,
            "name": f"{cam_name}.png",
        })
        
        # Subsample dense points from this view into world coordinates
        xyz, rgb = _subsample_points_by_confidence(
            pts3d_world[i], colors[i], conf_self[i],
            max_points=max_points_per_view
        )
        
        for j in range(len(xyz)):
            all_points[point_id_counter] = {
                "xyz": xyz[j],
                "rgb": rgb[j],
                "error": 0.0,
            }
            point_id_counter += 1
    
    print(f"Total initialization points: {len(all_points)}")
    
    # Write COLMAP binary files
    write_cameras_binary(colmap_cameras, sparse_dir / "cameras.bin")
    write_images_binary(colmap_images, sparse_dir / "images.bin")
    write_points3D_binary(all_points, sparse_dir / "points3D.bin")
    print(f"✅ COLMAP-compatible sparse model written to {sparse_dir}")
    
    # Also write COLMAP text files to manual/ for preprocess.py compatibility
    with open(manual_dir / "cameras.txt", "w") as f:
        for cam in colmap_cameras:
            f.write(f"{cam['id']} PINHOLE {cam['width']} {cam['height']} "
                    f"{cam['fx']} {cam['fy']} {cam['cx']} {cam['cy']}\n")
    
    with open(manual_dir / "images.txt", "w") as f:
        for img in colmap_images:
            qstr = " ".join(map(str, img["qvec"]))
            tstr = " ".join(map(str, img["tvec"]))
            f.write(f"{img['id']} {qstr} {tstr} {img['camera_id']} {img['name']}\n\n")
    
    with open(manual_dir / "points3D.txt", "w") as f:
        pass  # Empty file — points are in binary
    
    print(f"✅ COLMAP text files written to {manual_dir}")
    
    # Step 5: Cleanup temp images
    if images_dir.exists():
        shutil.rmtree(images_dir)
    
    # Free GPU memory
    del model
    torch.cuda.empty_cache()
    
    print(f"✅ CUT3R pose generation complete for {video_folder}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Generate poses_bounds.npy for 4D Gaussian Splatting")
    parser.add_argument("--folder", type=str, help="Folder of videos (legacy)")
    parser.add_argument("--source", type=str, help="Path to video or folder")
    parser.add_argument("--output", type=str, default="poses_bounds.npy")
    parser.add_argument("--size", type=int, default=512)
    parser.add_argument("--device", type=str, default="cuda")
    parser.add_argument("--num_frames_per_video", type=int, default=30)
    
    # Method selection
    parser.add_argument("--use_cut3r", action="store_true",
                        help="Use CUT3R for pose estimation (default: use COLMAP)")
    parser.add_argument("--cut3r_model_path", type=str, default=str(CUT3R_DEFAULT_CKPT),
                        help="Path to CUT3R checkpoint")
    parser.add_argument("--max_points_per_view", type=int, default=4000,
                        help="Max points per view for CUT3R initialization")

    
    # Legacy COLMAP flag (kept for backward compatibility)
    parser.add_argument("--use_colmap_poses", action="store_true",
                        help="Use COLMAP+LLFF for pose estimation (default behavior)")
    
    args = parser.parse_args()
    
    source = args.source if args.source else args.folder
    if not source:
        print("Error: --source or --folder required")
        sys.exit(1)
    
    try:
        if args.use_cut3r:
            print("=" * 60)
            print("Using CUT3R for pose estimation")
            print("=" * 60)
            generate_poses_cut3r(
                source, args.output,
                model_path=args.cut3r_model_path,
                device=args.device,
                size=args.size,
                max_points_per_view=args.max_points_per_view,
            )
        else:
            print("=" * 60)
            print("Using COLMAP for pose estimation (default)")
            print("=" * 60)
            generate_poses_colmap(source, args.output)
    except Exception as e:
        print(f"FATAL ERROR: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)
